FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
ENV TZ=America/Sao_Paulo
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT false
RUN apk update
RUN apk add --no-cache icu-libs
RUN apk add --no-cache tzdata
ENV LC_ALL pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
RUN apk add tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY /app .
EXPOSE 80
ENTRYPOINT ["dotnet", "RIPE.API.dll"]