 -- INSERT IN TABLE collateral_priority

USE collateral;
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('TD', 'SELIC', 1, 'Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('TD', 'IPCA', 1, 'Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('TD', 'PRE', 1, 'Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('CDB', 'VENCIMENTO', 3, 'Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('CDB', 'LIQUIDEZ DIARIA', 4, 'Baixa - Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('LC', 'VENCIMENTO', 3, 'Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('LCI', 'VENCIMENTO', 3, 'Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('LCA', 'VENCIMENTO', 3, 'Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('LF', 'VENCIMENTO', 3, 'Media', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Ações', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Cambial', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Multimercados', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Crédito Privado', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Investimento no Exterior', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Referenciado DI', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `collateral`.`collateral_priority` (`product_type_id`, `product_type_description`, `priority_scale`,`priority_scale_description`, `creation_date`, `update_date`) VALUES ('FUNDOS', 'Renda Fixa', 2, 'Media - Alta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
